version: "3.3"

services:
  
  app:
    container_name: frexco-app
    build:
      context: .
      dockerfile:
        Dockerfile
    ports:
      - "4123:4000"
    networks:
      - frexco-net

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - frexco-net 

networks:
  frexco-net: